parameters:
  postCustomEnvironmentVariables: []
  postBuild: []
  postSpecs: []
  preSpecsReport: []
  postPack: []
  vmImage: ''
  service_connection_nuget_org: '' 
  service_connection_github: '' 
  solution_to_build: ''

jobs:
- job: Build
  pool:
    vmImage: ${{ parameters.vmImage }}

  variables:
    BuildConfiguration: 'Release'
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
    SolutionToBuild: ${{ parameters.solution_to_build }}

    # We have dependencies on the following Environment Variables:
    # GITVERSION_PRERELEASETAG
    # BUILD_REPOSITORY_NAME

    # We have dependencies on the following Build Variables:
    # Endjin_Service_Connection_NuGet_Org
    # Endjin_Service_Connection_GitHub
    # Endjin.ForcePublish
  steps:
  - template: install.dotnet-global-tools.workaround.yml
  - template: install-and-run-gitversion.yml

  - powershell: |
      Write-Host "##vso[task.setvariable variable=Endjin_IsPreRelease]$((-not ([string]::IsNullOrEmpty($Env:GITVERSION_PRERELEASETAG))))"
      Write-Host "##vso[task.setvariable variable=Endjin_Repository_Name]$Env:BUILD_REPOSITORY_NAME"
    displayName: 'Set Environment Variables'

  - ${{ parameters.postCustomEnvironmentVariables }}

  # Useful for debugging purposes
  #- powershell: 'gci Env:'
  #  displayName: 'Print Environment Variables'

  - task: DotNetCoreCLI@2
    displayName: 'Restore & Build'
    inputs:
      command: 'build'
      projects: $(SolutionToBuild)
      arguments: '--configuration $(BuildConfiguration) /p:Version=$(GitVersion.SemVer)'
      versioningScheme: byBuildNumber

  - ${{ parameters.postBuild }}

  - task: DotNetCoreCLI@2
    displayName: 'Run Executable Specifications'
    inputs:
      command: 'test'
      projects: $(SolutionToBuild)
      arguments: '-c $(BuildConfiguration) --no-restore /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura'
      nobuild: true

  - ${{ parameters.preSpecsReport }}

  - script: |
      dotnet tool install -g dotnet-reportgenerator-globaltool
      reportgenerator "-reports:$(Build.SourcesDirectory)/**/**/coverage.cobertura.xml" "-targetdir:$(Build.SourcesDirectory)/CodeCoverage" "-reporttypes:HtmlInline_AzurePipelines;Cobertura"
    displayName: 'Generate Code Coverage Report'

  - task: PublishCodeCoverageResults@1
    displayName: 'Publish Code Coverage Report'
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: '$(Build.SourcesDirectory)/CodeCoverage/Cobertura.xml'
      reportDirectory: '$(Build.SourcesDirectory)/CodeCoverage'

  - ${{ parameters.postSpecs }}

  - task: DotNetCoreCLI@2
    displayName: 'Create NuGet Packages'
    inputs:
      command: 'pack'
      projects: $(SolutionToBuild)
      packDirectory: '$(Build.ArtifactStagingDirectory)/Packages/$(Build.BuildID)'
      nobuild: true
      versioningScheme: byEnvVar
      versionEnvVar: GitVersion.SemVer

  - ${{ parameters.postPack }}

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Packages'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/Packages'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Deployment Assets'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/Deployments'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Additional Release Assets'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/AdditionalReleaseAssets'

  - task: NuGetToolInstaller@0
    inputs:
      versionSpec: '5.1.0'

  - task: GithubRelease@0 
    displayName: 'Create GitHub Release'      
    condition: and(succeeded(), or(variables['Endjin.ForcePublish'], eq(variables['GitVersion.PreReleaseTag'], '')))
    inputs:
      gitHubConnection: ${{ parameters.service_connection_github }}
      repositoryName: $(Endjin_Repository_Name)
      tagSource: manual
      tag: $(GitVersion.SemVer) 
      isPreRelease: $(Endjin_IsPreRelease)
      assets: |
          $(Build.ArtifactStagingDirectory)/Packages/**/*.nupkg
          $(Build.ArtifactStagingDirectory)/Packages/**/*.snupkgs
          $(Build.ArtifactStagingDirectory)/AdditionalReleaseAssets/**
          $(Build.ArtifactStagingDirectory)/Deployments/**

  - task: NuGetCommand@2
    displayName: 'Publish to nuget.org'
    condition: and(succeeded(), or(variables['Endjin.ForcePublish'], eq(variables['GitVersion.PreReleaseTag'], '')))
    inputs:
      command: push
      nuGetFeedType: external
      publishFeedCredentials: ${{ parameters.service_connection_nuget_org }}
      versioningScheme: byBuildNumber
      packagesToPush: '$(Build.ArtifactStagingDirectory)/Packages/**/*.nupkg'